### ISSUE TITLE
Make GCC work

### ISSUE THREAD

**Issue by Thalhammer** [Thalhammer/simcom_dam#1]
For some reason I don't know yet, the builds produced by GCC do not work.
They compile fine and a quick inspection of the generated file shows no obvious problems and yet when one tries to use it the module gets bricked and a hard reset is required (which makes trial and error debugging quite a challenge).
However, the problem is definitely not with objcopy since when used with the elf generated using armcc it generates exactly the same result as fromelf (md5sum match).
So there must be something wrong with the generated code.
Can't validate linking since the object files generated by armcc don't work with normal ld.

**Comment by Thalhammer** [comment]
The module no more crashes, but uart only sends garbage for some reason. The same code compiled using armcc works fine. However I can't see any obvious differences in the generated asm.

**Comment by Thalhammer** [comment]
Figured it out :smile:
It does not like -mabi=apcs-gnu, leaving it out it seems to work fine.

**Comment by ziron4** [comment]
Did you get the gcc compiled application to work?
