### ISSUE TITLE
AT command necessary for location example to work?

### ISSUE THREAD

**Issue by jasongao** [Thalhammer/simcom_dam#6]
Is the location example supposed to work out-of-the-box? I noticed that my location tracking callback never gets called, unless I manually enable GNSS/GPS with `AT+CGNSPWR=1`. Is that the same behavior you're seeing?

**Comment by Thalhammer** [comment]
For me, the examples work as is with no separate AT commands required.
However, I already tried various things on the module, so it is possible that I have some configuration which is no more factory default.

If the AT command is really required you can send it from inside your app using the visual_at module.

**Comment by Thalhammer** [comment]
Did you solve this ?

**Comment by jasongao** [comment]
Yes, I think I just needed to wait longer, no AT commands were required in the end. Thanks!
